### ISSUE TITLE
unable to find the value of "choices"

### ISSUE THREAD

**Issue by night3759** [Yue-Yang/ChatGPT-Siri#1]
Thank you for your job, but I meet a bug. When I used it, it said:"unable to find the value of choices"(找不到词典键“choices”的值)

**Comment by Yue-Yang** [comment]
应该是 api 没有返回值，国内的话 api.openai.com 被 ban 了，连不上，把这个域名加入代理试试
  - DOMAIN-SUFFIX,api.openai.com,Proxy

**Comment by night3759** [comment]
> 

这回变成网络连接中断了

**Comment by Yue-Yang** [comment]
https://api.openai.com/，会返回一个 error message 的 json
你看你能打开这个网址吗，或者 ping 一下

**Comment by Yue-Yang** [comment]
那就不好确定了。应该还是网络问题。你走全局，或者换换网络试下吧

**Comment by night3759** [comment]
> 那就不好确定了。应该还是网络问题。你走全局，或者换换网络试下吧

他返回值是“”，空的，会不会是那个请求返回需要手动点击验证？我走了代理，正常的chatgpt都可以用，就是这个请求的返回值为空

**Comment by Yue-Yang** [comment]
刚开始第一次运行要允许「快捷指令」访问那个api
建议里重新下一个快捷指令，试试吧。中英文都试试，api key 也检查下，我都从 GitHub 上面的地址下载，测试过，没问题

**Comment by night3759** [comment]
> 刚开始第一次运行要允许「快捷指令」访问那个api 建议里重新下一个快捷指令，试试吧。中英文都试试，api key 也检查下，我都从 GitHub 上面的地址下载，测试过，没问题

我测试了半天，发现是我的api的问题，我用别人的api是可以实现的，但是我自己的api每次就不返回值，不知道为什么，API的获取步骤也是从官方那边生成的

**Comment by Yue-Yang** [comment]
api key，你可以重新生成一个新的试试。看看你有没有额度？新用户 $18 美元免费额度，用完要绑卡

**Comment by night3759** [comment]
> api key，你可以重新生成一个新的试试。看看你有没有额度？新用户 $18 美元免费额度，用完要绑卡

3/1号到期了，好吧，谢谢
