### ISSUE TITLE
用Hey,Siri唤醒似乎不是chatgpt，而是普通siri，用点击打开快捷指令正常运行

### ISSUE THREAD

**Issue by Ssiswent** [Yue-Yang/ChatGPT-Siri#10]
![image](https://user-images.githubusercontent.com/37449310/222903403-fb9ff513-03c6-45ac-800e-43b69401e794.png)

![image](https://user-images.githubusercontent.com/37449310/222903396-4529954e-6d68-4248-99ab-909a3ec2b54f.png)

如图，问你是谁，回答的是我是siri，而且不能连续对话，问问题也是给我说的safari找到的内容

**Comment by Yue-Yang** [comment]
你第一张图就是在我的快捷指令的提示，等你说话，就能对答。不确定你是不是误操作，退出了快捷指令，就是普通Siri了

你要听下提示音，为你服务，然后 ”回答完毕，请继续“

**Comment by Yue-Yang** [comment]
还有就是提示你说话的时候，你不能停留等待太长，不然好像会退出快捷指令了，这样只能重新开始新聊天了

**Comment by cyhhao** [comment]
我也是这样不知道为什么。出来第一个提示语之后我没退出马上说话，相应的还是Siri

**Comment by cyhhao** [comment]
怀疑是快捷指令导入的bug，可能导入遗失了一些信息。
所以想请教几个问题：

1. 我导入后第一行是这样的，这个正常吗？
![762CF638-5947-47B8-AE82-1314F3EC6F0B](https://user-images.githubusercontent.com/5381613/223003363-59e51022-d6e9-4f22-8cb4-d56486faaf40.jpeg)

2. 这一行的这个变量看起来也不合理，不知道是否影响
![0D9AE416-AE83-4F1F-9E8B-E38A107A9A55](https://user-images.githubusercontent.com/5381613/223003493-24493bdc-f024-472f-a790-bb4809497081.png)

3. 想知道通过语音回复Siri就能获得文本输入的语句是哪行语句？是不是这一行？
![D0292B1E-C885-4144-9FB8-83DE2D87A5B1](https://user-images.githubusercontent.com/5381613/223003783-93e225e9-51c5-46f2-b853-5ab0fbbcc52e.jpeg)

我review了整个代码逻辑好像只会走到这里，但这行不是应该是单独运行脚本的时候弹出的输入框吗？难道它会自动根据入口不同，从Siri运行就会语音转文字作为输入？

**Comment by lldong** [comment]
应该是 Siri 的 bug，参考这个[视频](https://www.bilibili.com/video/BV1bQ4y1N7b6/?spm_id_from=autoNext)里的操作就可以了：设置 > Siri 与搜索 > Siri 回答 > 始终显示你与 Siri 说的话 ，我把开关打开后就可以出发了，随后可以再关闭这个开关不影响触发

**Comment by cyhhao** [comment]
> 应该是 Siri 的 bug，参考这个[视频](https://www.bilibili.com/video/BV1bQ4y1N7b6/?spm_id_from=autoNext)里的操作就可以了：设置 > Siri 与搜索 > Siri 回答 > 始终显示你与 Siri 说的话 ，我把开关打开后就可以出发了，随后可以再关闭这个开关不影响触发

😭，还是不行

**Comment by Yue-Yang** [comment]
就是那里 接受输入，Siri启动就是语音输入，点击启动就是对话框输入，这个是自动适配的。

你需要唤醒 Siri后，说出 快捷指令的名字，才能启动。Siri 回答里面设置为自动，有一个是静音还有朗读

**Comment by xmfbit** [comment]
下载最新v1.2的话，需要改下名字，例如将其改名为 芝麻开门，这样才能通过Siri芝麻开门唤起

**Comment by xmfbit** [comment]
另外需要手动触发一次，允许openai的网络访问权限
