### ISSUE TITLE
用siri模式一直问我"备忘录是什么"我yue😭

### ISSUE THREAD

**Issue by edisonX-sudo** [Yue-Yang/ChatGPT-Siri#11]
用文字模式会让我选备忘录,我也可以点击. 但siri就蒙了,一直问我备忘录是什么 我照读也没用
![image](https://user-images.githubusercontent.com/8627326/222914056-e00167a2-e43d-4453-b7a0-309a1c093c21.png)

**Comment by Yue-Yang** [comment]
你可以选新版
