### ISSUE TITLE
iphone 13 pro max ,执行直接提示文件不存在

### ISSUE THREAD

**Issue by wjt1** [Yue-Yang/ChatGPT-Siri#12]
下载了1.2，执行后，问问题提示“文件不存在”

**Comment by Yue-Yang** [comment]
打开iCloud 试试，聊天记录文件是存在iCloud里。没开可能创建不了，就不能继续

**Comment by wjt1** [comment]
> 打开iCloud 试试，聊天记录文件是存在iCloud里。没开可能创建不了，就不能继续

我用了，1.0版本就可以正常使用，不知道为什么？看不懂快捷指令。

**Comment by wjt1** [comment]
> > 打开iCloud 试试，聊天记录文件是存在iCloud里。没开可能创建不了，就不能继续
> 
> 我用了，1.0版本就可以正常使用，不知道为什么？看不懂快捷指令。

1.2版本，可以到欢迎提示，然后继续输入内容，就提示“文件不存在了”，在其他iPhone 和mac上使用没有问题，但是就在13 promax上不行。

**Comment by Yue-Yang** [comment]
在 设置 iCloud 里面 打开 iCloud 云盘，开关。聊天记录需要创建在这这里面
