### ISSUE TITLE
代理

### ISSUE THREAD

**Issue by chinasilva** [Yue-Yang/ChatGPT-Siri#13]
能否支持代理地址，替换掉原始： https://api.openai.com/v1/chat/completions。自己服务器包了一层api，但是如果直接替换掉快捷方式的url没有返回值，在别的支持chatgpt工具中可以调通

**Comment by Yue-Yang** [comment]
你的接口跟官方一样，你替换应该没问题吧。我没弄过不清楚了

**Comment by chinasilva** [comment]
是一样的，但是直接返回回答完毕，其实没有任何别的输出

**Comment by Yue-Yang** [comment]
那需要你自己调试
