### ISSUE TITLE
可多一個繁體中文版本

### ISSUE THREAD

**Issue by wastu01** [Yue-Yang/ChatGPT-Siri#14]
有一些繁體中文用法不太一樣 感謝大大
目前是自己手動修改用語~

**Comment by Yue-Yang** [comment]
嗯，可以自己修改。主要语言太多了，也不好改

**Comment by Yue-Yang** [comment]
你可以把自己修改的，去掉key 链接发出来，我贴在后面，繁体的 链接

**Comment by wastu01** [comment]
Macos 環境下雲端設定打開了回覆紀錄沒有顯示在 txt 中
只顯示如圖資訊
<img width="813" alt="截圖 2023-03-07 上午12 16 01" src="https://user-images.githubusercontent.com/47618277/223168130-7a88871c-fdce-40c6-ace7-17f967520852.png">

**Comment by wastu01** [comment]
https://www.icloud.com/shortcuts/10f62e70be074707acd872b7b3390144 @Yue-Yang

**Comment by wastu01** [comment]
https://www.icloud.com/shortcuts/ca0eda24dab14870affb270d286dbfbd
