### ISSUE TITLE
在中找不到choice

### ISSUE THREAD

**Issue by fandongtongxue** [Yue-Yang/ChatGPT-Siri#17]
![image](https://user-images.githubusercontent.com/21986591/223750313-0ce1bf26-e74f-4884-a8e5-ec48bf814b6c.png)

**Comment by Yue-Yang** [comment]
https://twitter.com/YueYangDev/status/1633828525219393539?s=20

检查你的 api 使用情况，确保帐户有余额，并且没有过期
