### ISSUE TITLE
same  error message as everybody else!

### ISSUE THREAD

**Issue by rtajiri3** [Yue-Yang/ChatGPT-Siri#19]
ther is nothing wrong with my api key. and ive tried multiple times with shortcut, but nothing seems to work, did this ever work fully for you?

**Comment by spobleteo** [comment]
No. Problem with dictionary choices. I have a paid API key and it doesn't work. Help! Best

**Comment by Yue-Yang** [comment]
https://twitter.com/YueYangDev/status/1633828525219393539?s=20

check your API usage, it's a paid sevrice provided by openai
