### ISSUE TITLE
我开启了shadowrocket 代理，即全局代理，但还是报 ssl 错误，无法与服务器建立连接。

### ISSUE THREAD

**Issue by Ghostwritten** [Yue-Yang/ChatGPT-Siri#2]
我通过google 手机可以登陆 chatGPT

**Comment by Yue-Yang** [comment]
#1 你看下这个吧。无非就是网络问题，API key 的问题了。你检查检查吧

**Comment by freyliu82** [comment]
有微信群吗

**Comment by Yue-Yang** [comment]
https://platform.openai.com/account/usage

查看自己 API key 的额度有没有，过期没。重复问题 看 #1
