### ISSUE TITLE
请问，如何修改成自己反向代理的URL呢？

### ISSUE THREAD

**Issue by xavierskip** [Yue-Yang/ChatGPT-Siri#22]
我直接修改了其中的api.openai.com的那个URL，但是用起来就错误。是哪里的问题呢？

我反向代理的URL可以在其他的工具上正常使用，看起来是正常的。

如何在快捷指令中修改使用呢？

**Comment by Yue-Yang** [comment]
不清楚，你需要自己测试

**Comment by xavierskip** [comment]
找到问题在哪了。iOS 快捷指令对于http2的支持有问题。

我之前用 nginx 搭建的代理配置如下

```
server {
       server_name api.x.com;
       listen 443 ssl http2;
       location /v1/ {
           proxy_pass https://api.openai.com/v1/;
           proxy_set_header Host api.openai.com;
           proxy_set_header X-Real-IP $remote_addr;
       }
}
```

method | http | https
-- | -- | --
快捷指令 GET | ✅ | ✅
快捷指令 POST | ✅ | ❌
浏览器 POST | ✅ | ✅
httpie POST | ✅ | ✅

其他的应用都可以正常使用api就快捷指令不可以。

我把nginx的配置修改去掉http2后就可以了。

**Comment by xavierskip** [comment]
找到原因了,我服务器上的nginx版本太老多年不更新。因为 Nginx 1.9.15~1.10.x 版本在处理 http2 的post请求上有个bug，具体讨论可以看这里：

- [谈谈 Nginx 的 HTTP/2 POST Bug](https://imququ.com/post/nginx-http2-post-bug.html)
- [被 http2 坑了一把,nginx 1.9.15/1.10.0 + http2 + post + safari 有严重 bug](https://v2ex.com/t/300566)
