### ISSUE TITLE
“ Could not evaluate the key path.”

### ISSUE THREAD

**Issue by giuliorap** [Yue-Yang/ChatGPT-Siri#23]
How to solve this ?
![CDC407C4-FDAF-4E34-A552-9D664598CCF1](https://user-images.githubusercontent.com/108014747/224062733-8abdd41d-4b3c-43e6-b2a2-1411ac2ec85b.png)
![373720F8-E84C-49D8-ACDE-83B8BE416F47](https://user-images.githubusercontent.com/108014747/224062798-ee168497-89bc-4e6c-a283-d16d22891056.png)

**Comment by Yue-Yang** [comment]
Please check your API usage at the following website to ensure that your account has sufficient balance and is not expired: [https://platform.openai.com/account/usage](https://t.co/WVQ4BQ6T6r). If your account does not have enough balance or has expired, you will need to link a payment method.
