### ISSUE TITLE
为啥我是Siri 无法执行快捷指令的应用

### ISSUE THREAD

**Issue by skykiah** [Yue-Yang/ChatGPT-Siri#27]
为啥我是Siri 无法执行快捷指令的应用

**Comment by Yue-Yang** [comment]
什么意思？你直接“嘿，Siri，智能聊天”，就可以了，就是说出名字，不过你需要Siri能识别准确，并匹配到名字。你可以打开Siri设置里面，总是显示我说的话，看看识别的怎么样

**Comment by skykiah** [comment]
我的意思是我的siri 无法唤起快捷指令的 智能聊天，不知道咋回事。

**Comment by Yue-Yang** [comment]
不说了吗，要匹配到名字。你可以到Siri设置里，打开显示自己说的话，看看识别的准不准
