### ISSUE TITLE
等待时间过长会报错

### ISSUE THREAD

**Issue by Bob-cheng** [Yue-Yang/ChatGPT-Siri#28]
如果回答的内容比较多，等待的时间太长，siri会报错。

**Comment by Yue-Yang** [comment]
报的啥错，一步一步是怎么出现的，能描述一下吗

**Comment by Bob-cheng** [comment]
比如让它讲一个故事，1000字左右，在等待回复的时候，siri会说: 稍等一下，仍在处理，仍在处理中，最后就是 出错了，请稍后再试。可能是chatGPT长时间没有完成作答，等待超时了。

**Comment by Yue-Yang** [comment]
那是你网络不好吧，没办法

**Comment by Bejukoro** [comment]
我这里也是相同的表现。
如果你询问的问题会使 ChatGPT 的回答较长，OpenAI 方面回传出完整回答的耗时也会变长，从而就可能造成快捷指令超时。
