### ISSUE TITLE
Error: this file doesnt exist

### ISSUE THREAD

**Issue by qphillo** [Yue-Yang/ChatGPT-Siri#32]
Hi, I'm getting this error. ![57EA4BBF-8EAD-4646-B437-DF1A67072E56](https://user-images.githubusercontent.com/101527474/224487337-9e9367b7-8ab1-4261-aa1d-8e754e89c1eb.jpeg)
What could cause it?

**Comment by Yue-Yang** [comment]
> Hi, I'm getting this error. ![57EA4BBF-8EAD-4646-B437-DF1A67072E56](https://user-images.githubusercontent.com/101527474/224487337-9e9367b7-8ab1-4261-aa1d-8e754e89c1eb.jpeg)
> 
> What could cause it?

You need to open 'Settings' - Apple ID - iCloud - iCloud Drive function to enable the feature of saving to txt file.
