### ISSUE TITLE
error: The file doesn't exist

### ISSUE THREAD

**Issue by Tawpie** [Yue-Yang/ChatGPT-Siri#36]
v1.2
iOS and MacOS

STEPS TO REPRO

1. load the shortcut
2. enter api key
3. open shortcut
4. enter New Chat (see welcome message)
5. enter a question [fails "The file doesn't exist" at step Run Chat input new-chat-command]

**Comment by Yue-Yang** [comment]
> v1.2
> 
> iOS and MacOS
> 
> 
> 
> STEPS TO REPRO
> 
> 
> 
> 1. load the shortcut
> 
> 2. enter api key
> 
> 3. open shortcut
> 
> 4. enter New Chat (see welcome message)
> 
> 5. enter a question [fails "The file doesn't exist" at step Run Chat input new-chat-command]

You need to open 'Settings' - Apple ID - iCloud - iCloud Drive function to enable the feature of saving to txt file.

**Comment by Tawpie** [comment]
Ah. Excellent, that does work! Thank you for your work, you’ll probably get a lot of attention from the articles that highlighted your efforts. Good for you!

Kim
