### ISSUE TITLE
On Mac ask Privacy each question, no Siri captions on Mac display

### ISSUE THREAD

**Issue by taiqn** [Yue-Yang/ChatGPT-Siri#41]
Hi, I installed version 1.2.2 on Macbook and it aksed for privacy each question, if not asked then could not connect. And is it possible to show Siri captions on Mac display like on iPhone? would be very nice - thanks

**Comment by Yue-Yang** [comment]
I use the default setting on mac and there are siri capitions shows on mac. So i dont know how to solve your problem.

**Comment by taiqn** [comment]
Btw, just use and it works now without privacy issue. Maybe just need to restart

**Comment by Yue-Yang** [comment]
check your mac siri's settings. i dont know how it fails to show captions. On my mac i can see the captions like iphone.
