### ISSUE TITLE
Could not evaluate the key path. In ", no value was found for dictionary key 'choices'.

### ISSUE THREAD

**Issue by dbdavid44** [Yue-Yang/ChatGPT-Siri#45]
![FD955D0B-180D-45E7-8CEA-6CC06EAE9E96](https://user-images.githubusercontent.com/128003019/225467305-e7076bb3-dd7e-4a3f-ba5d-f52f5de45f1a.jpeg)
![D78330ED-5E2F-4D00-A582-B8B021F62E08](https://user-images.githubusercontent.com/128003019/225467310-a8ffe64a-2a8b-4c23-848b-5c01350458ff.png)

@Yue-Yang I wasn’t able to identify the source of the issue but here are a couple of screenshots. This happens during first use.

**Comment by jeffscottmtl** [comment]
I had the same problem. In my case it happened because I was out of free
credits. Subscribing resolved the issue.

**Comment by Yue-Yang** [comment]
https://github.com/Yue-Yang/ChatGPT-Siri/discussions/30
