### ISSUE TITLE
用了一次，直接导致openai账户被ban...

### ISSUE THREAD

**Issue by aboutsome** [Yue-Yang/ChatGPT-Siri#47]
用了一次，直接导致openai账户被ban...之前网页版chatGPT一直没事。今天用了下这个，通过apiKey，直接被ban了...大无语

**Comment by Yue-Yang** [comment]
> 用了一次，直接导致openai账户被ban...之前网页版chatGPT一直没事。今天用了下这个，通过apiKey，直接被ban了...大无语

你找你自己原因。跟快捷指令没任何关系
