### ISSUE TITLE
iPhone/Mac - same error "Could not evaluate the key path."

### ISSUE THREAD

**Issue by LowRezSkyline** [Yue-Yang/ChatGPT-Siri#48]
In '', no value was found for dictionary key 'choices'. 

I tried on both iOS (iPhone) and Mac.

Also, seems to be hardcoded for GPT 3.5 looking at the shortcut, might want to make that another editable option.

Interesting idea.

**Comment by Yue-Yang** [comment]
> 
> 
> 
> 
> In '', no value was found for dictionary key 'choices'. 
> 
> 
> 
> I tried on both iOS (iPhone) and Mac.
> 
> 
> 
> Also, seems to be hardcoded for GPT 3.5 looking at the shortcut, might want to make that another editable option.
> 
> 
> 
> Interesting idea.

https://github.com/Yue-Yang/ChatGPT-Siri/discussions/30 look at it
