### ISSUE TITLE
找不到choice值

### ISSUE THREAD

**Issue by stormdush** [Yue-Yang/ChatGPT-Siri#52]
系统IOS16.3
![4E2EE353-4F7E-4088-8ED6-91EAECF7CF82](https://user-images.githubusercontent.com/8814485/225814793-9330823d-de9e-4da5-a69e-573bffb9dda4.png)
![B30A725D-F79B-49C8-9315-AF80CBCC2390](https://user-images.githubusercontent.com/8814485/225814795-91e6b4b7-bc7e-45a1-8bec-8cc217a854d7.png)

版本1.2.2

**Comment by shaobaili3** [comment]
same issue

**Comment by Yue-Yang** [comment]
你看下注意：国内已经不能访问 api 了，需要开代理！查看「连接问题」「找不到key」：https://github.com/Yue-Yang/ChatGPT-Siri/discussions/29。都有写，仔细看看
