### ISSUE TITLE
Chat moves on fast. It's not practical... ask for something then after 3-5 seconds it will prompt "can I help you with something else".

### ISSUE THREAD

**Issue by JediMasterino** [Yue-Yang/ChatGPT-Siri#54]

**Comment by Yue-Yang** [comment]
Please provide a detailed description of the process and steps, preferably with screenshots.

**Comment by JediMasterino** [comment]
Steps are as followed:

1) press Siri button 
2) say the name of the shortcut for example chatgpt to activate it
3) shortcut gets activated and then I proceeded with my question
4) chatgpt answers the question 
5) I'm reading the answer but immediately I get interrupted by the chatgpt asking me if I want anything. 
![image](https://user-images.githubusercontent.com/93412934/226108198-4b119ea9-d524-4b8a-aef1-71690e822a71.png)
![image](https://user-images.githubusercontent.com/93412934/226108204-616079e0-18b1-47c8-b2bf-1d9a50d9ce25.png)
![image](https://user-images.githubusercontent.com/93412934/226108212-f1d8982e-102b-4816-9b4f-9de89f4809f2.png)
![image](https://user-images.githubusercontent.com/93412934/226108219-3adfd1d7-d9fc-4b93-86b5-b71d7d5c17a5.png)

**Comment by vinta** [comment]
@JediMasterino Ah, I think we're talking about the same issue!
https://github.com/Yue-Yang/ChatGPT-Siri/discussions/60
