### ISSUE TITLE
Error - could not ealuate the key path

### ISSUE THREAD

**Issue by difanzhao** [Yue-Yang/ChatGPT-Siri#64]
Hi Yue-yang, I got it working on my iPhone 11 but having an issue with my iPhone 8... I would get this error:

`Could not evaluate the key path,
in "'', no value was found for dictionary key 'choices'. `

Please help! Thanks!

**Comment by difanzhao** [comment]
never mind. I found issue #30 and I checked the account and there is no money there... I didn't know that they charge for API uses. My other account got 18$ automatically for some reason and this one didn't... Will figure it out and report back. Sorry for the spam!

**Comment by XOKP** [comment]
The $18 was allocated to early users, it has since been discontinued after the increased popularity of ChatGPT.

**Comment by difanzhao** [comment]
I see. Much appreciated for the info!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
