### ISSUE TITLE
错误提示，无法使用。

### ISSUE THREAD

**Issue by slwl** [Yue-Yang/ChatGPT-Siri#7]
找不到词典键choices的值

**Comment by freyliu82** [comment]
我也是

**Comment by freyliu82** [comment]
发现了，key被污染了，有问题

**Comment by cybergoat520** [comment]
There was a problem running the shortcut“智能聊天”.       这个是不是icloud权限问题啊，但是没提示我授权啊，我该怎么办

**Comment by goodtiger** [comment]
同样的问题，
找不到词典键choices的值

**Comment by Yue-Yang** [comment]
看 #1 的。
一个网络问题，一个key问题。然后确保 API key 有使用额度：https://platform.openai.com/account/usage
