### ISSUE TITLE
the reply disappears too much and there is no siri reading of the text

### ISSUE THREAD

**Issue by YubinXie** [Yue-Yang/ChatGPT-Siri#9]
Hi thanks for this amazing repo. It is great and i have some suggestion:
1. keep the reply on the display until we finish next command. There is not enough time to finish reading with current short timing.
2. siri reads the message from chat gpt.

**Comment by YubinXie** [comment]
i tried to adjust the repeat time, and turned off the mute mode. both problems are gone. it could be some iphone issue.

**Comment by drbilo** [comment]
Also have the above two issues

**Comment by Yue-Yang** [comment]
The capabilities of Siri are limited and cannot be controlled freely. If you want to see the records, you can check them in Notes or Files after the conversation is over. Alternatively, you can choose to use Shortcuts by clicking, which allows you to control the display time freely.
