### ISSUE TITLE
feature request:modify API HOST

### ISSUE THREAD

**Issue by iamsad3508** [Yue-Yang/ChatGPT-Siri#97]
there is way to setup a CLOUDFLARE WORKS to bypass gfw ,so it's better to modify api address when setting up 
CF WORKER能过墙代理api地址啦，不用整天挂小火箭啦，要不在设置api key之后增加一个设置api 地址的？

**Comment by Yue-Yang** [comment]
小火煎，你可以分流啊。为啥要关呢……
改api地址，你可以打开快捷指令编辑，然后自己修改
